kind: pipeline
type: kubernetes
name: default

steps:

- name: build
  image: golang:1.13
  commands:
    - "go build -o ./myapp"

- name: publish  
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: sorted78/vmware-demo
    tags:
      - 3.0
