name: default
kind: pipeline
type: docker

steps:
- name: testing
  image: golang
  commands:
  - go test
     
- name: build
  image: golang
  commands:
  - go build -o ./myapp
  
- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: sorted78/vmware-demo
    tags:
      - 1.0.2
      - latest
  when:
    branch:
    - master
