name: default

kind: pipeline
type: docker

steps:
- name: backend
  image: golang
  commands:
    - go get
    - go build ./myapp
    - go test

- name: publish
  image: plugins/docker
  settings:
    repo: sorted78/vmware-demo
    tags: [ 1, 1.1, latest ]
    registry: index.docker.io
